service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
  region: ap-southeast-2
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/index.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
          cors: true
      - httpApi:
          path: /
          method: GET
          cors: true
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript